import pandas as pd
import pandas_ta as ta # Technical Analysis library

def add_technical_features(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()

    # --- 1. Trend & Momentum ---

    # Using the PANDAS-TA extension syntax (df.ta.function_name)

    # Moving Averages (These functions modify the DF in place if append=True)
    df.ta.ema(close='close', length=12, append=True) # Adds column 'EMA_12'
    df.ta.ema(close='close', length=26, append=True) # Adds column 'EMA_26'
    df.ta.sma(close='close', length=50, append=True) # Adds column 'SMA_50'
    df.ta.sma(close='close', length=200, append=True) # Adds column 'SMA_200'

    # MACD
    df.ta.macd(close='close', fast=12, slow=26, signal=9, append=True)
    # Adds columns like 'MACD_12_26_9', 'MACDs_12_26_9', 'MACDh_12_26_9'

    # Relative Strength Index (RSI)
    df.ta.rsi(close='close', length=14, append=True) # Adds column 'RSI_14'

    # --- 2. Volatility ---

    # Average True Range (ATR)
    df.ta.atr(length=14, append=True) # Adds column 'ATR_14'

    # Bollinger Bands (Suite provides lower band, middle band (SMA), and upper band)
    df.ta.bbands(close='close', length=20, std=2, append=True)

    # --- 3. Volume ---

    # Volume EMA (Use 'alias' to specify a custom column name if needed)
    df.ta.ema(close='volume', length=20, alias='vol_ema_20', append=True)
    
    # On-Balance Volume (OBV)
    df.ta.obv(close='close', volume='volume', append=True)

    # --- 4. Time Features ---
    
    # Ensure the index is a datetime object
    if not isinstance(df.index, pd.DatetimeIndex):
        df.index = pd.to_datetime(df.index)
        
    df['hour'] = df.index.hour
    df['day_of_week'] = df.index.dayofweek # 0=Monday, 6=Sunday
    df['is_weekend'] = (df.index.dayofweek >= 5).astype(int) # Binary 0 or 1

    # Drop rows with NaN values generated by window functions
    df.dropna(inplace=True)

    return df
